daily_digest_job:
 cron: "0 8 * * *"
 class: DailyDigestJob
 description: "daily digest"
 queue: main
 args:
 
weekly_digest_job:
 cron: "0 7 * 1 *"
 class: WeeklyDigestJob
 description: "daily digest"
 queue: main
 args: